#!/usr/bin/env bash
# A script that starts a nvim remote server using the tmux pane as an identifier

if [[ !(-n ${TMUX}) ]]; then
    echo "You're not inside a tmux session"
    exit 1
fi

NVIM_SERVER_PIPE=$(echo "/tmp/nvim-tmux-${TMUX_PANE}.pipe")
nvim --listen "${NVIM_SERVER_PIPE}" $@
