#!/bin/bash
selected=$(tmux list-sessions | fzf)

if [[ -z $selected ]]; then
    exit 0
fi

session_name=$(echo $selected | sed -r 's/^(.*): .*$/\1/')

if [[ -z $TMUX ]]; then
    tmux attach-session -t $session_name
else
    tmux switch-client -t $session_name
fi
