promptToReturnFromSubprocess: false
gui:
  showIcons: true
git:
  paging:
    colorArg: never
    useConfig: false
    pager: delta --dark --paging=never
os:
  editCommand: 'lazygit-editor' # Uses my custom script
  editCommandTemplate: '{{editor}} {{filename}}' # for tmux and nvim remote integration
